import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar'
import { Toaster } from "@/components/form/Toaster"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { CSPostHogProvider } from './providers'
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body> 
      <Navbar />
      <CSPostHogProvider>
      {children}
      </CSPostHogProvider>
      <Footer />
      <Toaster />
      <Analytics/> 
      <SpeedInsights/>
    </body>
  </html>
  );
}
