import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar'
import { Toaster } from "@/components/form/Toaster"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body> 
      <Navbar />
      {children}
      <Toaster />
      <Analytics/> 
      <SpeedInsights/>
    </body>
  </html>
  );
}
