"use client";
import React from 'react';
import { motion } from 'framer-motion';
import { Smile, Zap, Target, MessageCircle, CheckCircle } from 'lucide-react';
import { Button } from "@/components/ui/button";

const RestOfHomepage = () => {
  const benefits = [
    { icon: <Smile className="w-8 h-8 text-indigo-600" />, title: "Personal Touch", description: "Our AI understands wedding dynamics and your unique relationship with the groom, ensuring a speech that feels genuine and heartfelt." },
    { icon: <Zap className="w-8 h-8 text-indigo-600" />, title: "Time-Saving", description: "Generate a full speech draft in minutes, not hours. More time for bachelor party planning!" },
    { icon: <Target className="w-8 h-8 text-indigo-600" />, title: "Perfect Balance", description: "Strike the ideal balance between humor and sentiment, tailored to your preferences and the wedding's tone." },
    { icon: <MessageCircle className="w-8 h-8 text-indigo-600" />, title: "Instant Feedback", description: "Get real-time suggestions and improvements as you refine your speech to perfection." },
  ];

  const howItWorks = [
    { step: 1, title: "Share Your Story", description: "Tell us about your relationship with the groom and any key memories or inside jokes." },
    { step: 2, title: "AI Magic", description: "Our specialized AI crafts a personalized speech draft based on your input and best practices for wedding speeches." },
    { step: 3, title: "Refine and Perfect", description: "Edit, tweak, and polish your speech with our interactive editor and AI suggestions tailored for wedding audiences." },
  ];

  const testimonials = [
    { name: "Alex Johnson", role: "Best Man", quote: "BestManAI saved my speech! I was struggling to find the right words, but the AI gave me an amazing starting point that I could easily personalize. It understood the wedding context way better than ChatGPT ever could." },
    { name: "Chris Lee", role: "Best Man", quote: "I'm not a natural writer, but this tool made me sound like a pro. The groom and all the guests loved my speech! The specialized wedding knowledge really showed in the final product." },
  ];

  const faqs = [
    { question: "How is BestManAI different from using ChatGPT?", answer: "Unlike general AI tools, BestManAI is specifically trained on thousands of successful wedding speeches. It understands wedding etiquette, appropriate humor, and the right balance of sentimentality. Our AI also offers specialized features like tone adjustment and audience-specific content suggestions that general AI tools simply can&apos;t match." },
    { question: "Can I see an example of a generated speech?", answer: "Absolutely! Here&apos;s a sample intro generated by BestManAI: &apos;Ladies and gentlemen, I&apos;ve known [Groom&apos;s Name] since we were five years old, and I can confidently say that [Bride&apos;s Name] is the best thing that&apos;s ever happened to him – besides me, of course! [Pause for laughter] But in all seriousness...&apos; You can generate a full custom sample on our Try It Free page." },
    { question: "What if I&apos;m not satisfied with the generated speech?", answer: "We offer a 100% satisfaction guarantee. If you&apos;re not happy with your speech after using our editing tools and AI suggestions, we&apos;ll provide a full refund. But with our 98% satisfaction rate, we&apos;re confident you&apos;ll love your BestManAI speech!" },
  ];

  return (
    <div className="bg-white">
      {/* Unique Selling Proposition */}
      <section className="bg-indigo-100 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-extrabold text-indigo-900 mb-4">Why BestManAI Beats General AI Tools</h2>
          <p className="text-xl text-indigo-700 mb-8">Specialized in wedding speeches, trained on thousands of successful best man toasts</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white p-4 rounded-lg shadow">
              <CheckCircle className="w-8 h-8 text-green-500 mx-auto mb-2" />
              <p>Wedding-specific language and etiquette</p>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <CheckCircle className="w-8 h-8 text-green-500 mx-auto mb-2" />
              <p>Appropriate humor and sentiment balance</p>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <CheckCircle className="w-8 h-8 text-green-500 mx-auto mb-2" />
              <p>Audience-tailored content suggestions</p>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">Why Choose BestManAI?</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="bg-indigo-50 p-6 rounded-lg"
              >
                <div className="mb-4">{benefit.icon}</div>
                <h3 className="text-xl font-semibold mb-2">{benefit.title}</h3>
                <p className="text-gray-600">{benefit.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="bg-indigo-100 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">How It Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {howItWorks.map((step, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: index * 0.2 }}
                className="bg-white p-6 rounded-lg shadow-md"
              >
                <div className="text-3xl font-bold text-indigo-600 mb-4">Step {step.step}</div>
                <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                <p className="text-gray-600">{step.description}</p>
              </motion.div>
            ))}
          </div>
          <div className="text-center mt-12">
            <Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-white transition-all duration-300 transform hover:scale-105">
              Try It Free
            </Button>
          </div>
        </div>
      </section>

      {/* Sample Output Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">See BestManAI in Action</h2>
          <div className="bg-gray-100 p-6 rounded-lg shadow-inner">
            <h3 className="text-xl font-semibold mb-4">Sample Speech Intro:</h3>
            <p className="text-gray-700 italic">
              &ldquo;Ladies and gentlemen, I&apos;ve known [Groom&apos;s Name] since we were five years old, and I can confidently say that [Bride&apos;s Name] is the best thing that&apos;s ever happened to him – besides me, of course! [Pause for laughter] But in all seriousness, watching these two fall in love has been like watching a real-life romantic comedy, minus the predictable plot and cheesy soundtrack...&rdquo;
            </p>
          </div>
          <div className="text-center mt-8">
            <Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-white transition-all duration-300 transform hover:scale-105">
              Generate Your Custom Intro Now
            </Button>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-indigo-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">What Best Men Are Saying</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5 }}
                className="bg-white p-6 rounded-lg shadow"
              >
                <p className="text-lg mb-4">&ldquo;{testimonial.quote}&rdquo;</p>
                <div className="font-semibold">{testimonial.name}</div>
                <div className="text-indigo-600">{testimonial.role}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">Simple, Transparent Pricing</h2>
          <div className="bg-white p-8 rounded-lg shadow-lg max-w-md mx-auto">
            <h3 className="text-2xl font-bold text-center mb-4">One-Time Fee</h3>
            <div className="text-4xl font-bold text-center text-indigo-600 mb-4">$49.99</div>
            <ul className="mb-8">
              <li className="flex items-center mb-2"><CheckCircle className="w-5 h-5 text-green-500 mr-2" /> Unlimited revisions</li>
              <li className="flex items-center mb-2"><CheckCircle className="w-5 h-5 text-green-500 mr-2" /> AI-powered suggestions</li>
              <li className="flex items-center mb-2"><CheckCircle className="w-5 h-5 text-green-500 mr-2" /> 24/7 customer support</li>
              <li className="flex items-center"><CheckCircle className="w-5 h-5 text-green-500 mr-2" /> 100% satisfaction guarantee</li>
            </ul>
            <Button size="lg" className="w-full bg-indigo-600 hover:bg-indigo-700 text-white transition-all duration-300 transform hover:scale-105">
              Get Started Now
            </Button>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="bg-gray-50 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-gray-900 text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-8">
            {faqs.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="bg-white p-6 rounded-lg shadow-md"
              >
                <h3 className="text-xl font-semibold mb-2">{faq.question}</h3>
                <p className="text-gray-600">{faq.answer}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA Section */}
      <section className="py-20 bg-indigo-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-extrabold text-white mb-4">Ready to Craft Your Legendary Speech?</h2>
          <p className="text-xl text-indigo-100 mb-8">Join thousands of best men who have delivered unforgettable speeches with BestManAI.</p>
          <Button size="lg" className="bg-white text-indigo-600 hover:bg-indigo-50 transition-all duration-300 transform hover:scale-105">
            Start Your Free Trial Now
          </Button>
        </div>
      </section>
    </div>
  );
};

export default RestOfHomepage;